apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-02
  namespace: kube-system
spec:
# DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-02
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr-02
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      containers:
        - name: k8s-bigip-ctlr-02
          image: "f5networks/k8s-bigip-ctlr"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef: 
                # Replace with the name of the Secret containing your login
                # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                # Replace with the name of the Secret containing your login
                # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about all config options
            # https://clouddocs.f5.com/containers/latest/
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.0.1.54",
            "--bigip-partition=k8s02",
            "--insecure",
            "--pool-member-type=nodeport",
            "--share-nodes=true",
            "--log-as3-response=true",
            "--disable-teems=true",
            "--hubmode=true",
            "--log-level=debug",
            "--namespace=nginx-app-02",
            #"--namespace=nginx-app-01",
            ]
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
