---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx01
  namespace: nginx01
  labels:
    app: nginx01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx01
  template:
    metadata:
      labels:
        app: nginx01
    spec:
      containers:
      - name:  nginx01
        #image: public.ecr.aws/z9d2n7e1/nginx:1.19.5
        image: 065972273535.dkr.ecr.us-west-2.amazonaws.com/jessed_ecr:jesse-nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx01
  namespace: nginx01
  labels:
    app:                    nginx01
    cis.f5.com/as3-tenant:  nginx01
    cis.f5.com/as3-app:     as3
    cis.f5.com/as3-pool:    p01-nginx
spec:
  type: NodePort
  selector:
    app: nginx01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx01-cfgmap
  namespace: nginx01
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.18.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "http",
        "remark": "",
        "nginx01": {
          "class": "Tenant",
          "as3": {
            "class": "Application",
            "template": "generic",
            "vs01-nginx": {
              "class":            "Service_HTTP",
              "virtualAddresses": [ "10.0.1.50" ],
              "pool":             "p01-nginx"
            },
            "p01-nginx": {
              "class": "Pool",
              "monitors": [ "icmp" ],
              "members": [{
                 "servicePort": 80,
                 "serverAddresses": []
                }]
            }
          }
        }
      }
    }
